baseurl = "https://alvamarkelius.github.io/"
title = "Alva J. K. Markelius"
author = "Alva Markelius"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Alva J. K. Markelius"
  disableWebFonts = false

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 20

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 30

  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 40

  [[menu.main]]
    name = "Talks & Press"
    url = "/talkspress/"
    weight = 50

  [[menu.main]]
    name = "Polo"
    url = "/polo/"
    weight = 60
