baseURL = "https://AlvaMarkelius.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "PaperMod"

[params]

  [params.profileMode]
    enabled = true
    title = "<Alva J. K. Markelius>"
    subtitle = "This is subtitle"
    imageUrl = "<image link>"
    imageTitle = "<title of image as alt>"
    imageWidth = 120
    imageHeight = 120

    [[params.profileMode.buttons]]
      name = "Archive"
      url = "/archive"

    [[params.profileMode.buttons]]
      name = "Github"
      url = "https://github.com/"

  [[params.socialIcons]]
    name = "<platform>"
    url = "<link>"

  [[params.socialIcons]]
    name = "<platform 2>"
    url = "<link2>"
